---
- hosts: localhost
  connection: local


  tasks:

    - name: Attach security group to instance
      script: lambda-invoked-attach-sg.py '{{aws_access_key}}' '{{aws_secret_key}}' '{{region}}' '{{inst_id}}'
